[tool.coverage.run]
source = ["sorl"]
omit = [
    "*/sorl-thumbnail/sorl/__init__.py",
    "*/sorl/thumbnail/__init__.py",
    "*/sorl/thumbnail/conf/__init__.py",
    "*/sorl/thumbnail/admin/__init__.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "if __name__ == .__main__.:",
]

[tool.ruff]
exclude = [
    ".tox",
    "docs/*",
    "*/migrations/*",
    "tests/settings/*",
    "sorl/thumbnail/__init__.py",
    "sorl/thumbnail/admin/__init__.py"
]
line-length = 100

[tool.ruff.lint]
select = ["B", "C901", "E", "F", "I", "W"]
ignore = ["B904", "B017"]

[tool.ruff.lint.mccabe]
max-complexity = 15
